channels:
  - conda-forge
  - defaults

dependencies:
  - ale =0.10.0,<1
  - armadillo
  - boost >=1.78.0,<1.79
  - boost-cpp >=1.78.0,<1.79
  - blas
  - usgs-astrogeology::bullet
  - bz2file
  - bzip2
  - cmake >=3.15
  - cspice=67
  - csm>=3.0.3,<3.0.4
  - curl
  - cxx-compiler=1.1.2
  - doxygen
  - eigen < 3.4
  - embree>=2.17,<3
  - ffmpeg
  - geos =3.11.1
  - geotiff
  - gmp
  - graphviz
  - gsl>=2.6, <2.7
  - hdf5
  - icu
  - inja
  - jama
  - jpeg
  - usgs-astrogeology::kakadu==1
  - krb5
  - libopencv >=4.7,<4.8
  - libpng>=1.6.34
  - libprotobuf
  - libtiff>=4.0
  - libxml2
  - make
  - mesalib
  - mysql
  - mysql-connector-c
  - nanoflann<1.4
  - nlohmann_json
  - ninja==1.7.2
  - nn
  - opencv>=4.5.2
  - openssl>=1.1.1k
  - pcl >= 1.10.0
  - protobuf
  - python >=3.10
  - python_abi >=3.10
  - pytest
  - qhull
  - qt-main >=5.15.8, <5.16
  - qwt <6.3.0
  - rclone
  - sqlite >=3.46.0,<3.47
  - suitesparse<7.7.0
  - superlu
  - swig
  - texlive-core
  - tnt
  - x264
  - xalan-c
  - xerces-c=3
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxi
  - zlib
